name: Kick Points Miner
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  run-miner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install cloudscraper loguru

      - name: Create Config File
        run: |
          echo '{
            "channels": ["${{ secrets.CHANNELS }}"],
            "authorization": "Bearer ${{ secrets.AUTH_TOKEN }}",
            "wait_times": {
              "livestream_active": { "min": 120, "max": 300 },
              "livestream_inactive": 300,
              "error_wait": 180
            },
            "messages": ["[emote:1730752:emojiAngel]", "[emote:1730753:emojiAngry]"]
          }' > config.json
